employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('currentemployees/', views.currentemployees, name='current_employees'),  # отображение всех созданых сотрудников
    path('createemployees/', views.createemployees, name='create_employees'),  # добавить сотрудника
    path('viewemployees/<int:employees_pk>', views.viewemployees, name='view_employees'),  # <int:employees_pk>/ - в адрес автомат-ки подставляет значение
    path('deleteemployee/<int:employee_pk>', views.deleteemployee, name='delete_employee'),
]

job_directory_project/urls.py
from django.contrib import admin
from django.urls import path, include
from job import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('currentjob/', views.currentjob, name='current_job'),  # отображение всех созданых должностей
    path('createjobtitle/', views.createjobtitle, name='create_jobtitle'),  # добавить должность
    path('viewjob/<int:job_pk>', views.viewjob, name='viewjob'),  # <int:job_pk>/ - в адрес автомат-ки подставляет значение
    path('deletejob/<int:job_pk>', views.deletejob, name='deletejob'),
    path('employees/', include('employees.urls'), name="employees_click")

]

job/models.py
from django.db import models

class Job(models.Model):
    job_title = models.CharField(max_length=100)  # в заголовках небольше 100символов
    job_category = models.CharField(max_length=100)

    created = models.DateTimeField(auto_now=True)  # отображается не только дата, но и время
    # auto_now=True - атрибут присваивается автоматически

    def __str__(self):  # функция в отображении панели админа возращает не номера проектов, а заголовок проекта
        return self.job_title

job/forms.py
from django.forms import ModelForm
from .models import Job  # модель для объектов

class JobTitleForm(ModelForm):
    class Meta:
        model = Job
        fields = ['job_title', 'job_category']  # что будем отображать - список

job/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import JobTitleForm  # импортируем нашу форму для страницы создания должностей пользователя createtodo
from .models import Job

def home(request):
    return render(request, 'job/home.html')

def createjobtitle(request):
    if request.method == 'GET':
        return render(request, 'job/create_job_title.html', {'form': JobTitleForm()})
    else:
        try:
            # выполняется если пользователь внес какую-то информацию в окно и нажал кнопку Create (Создать)
            form =JobTitleForm(request.POST)  # соединить внесенную информацию с нашей формой
            newjobtitle = form.save(commit=False)  # даная форму сохраняет информацию в базу данных
            # делаем привязку созданной записи к конкрутному пользователю
            newjobtitle.user = request.user
            newjobtitle.save()  # сохранит привязку в БД
            return redirect('current_job')  # перенаправить пользователя на список доступных должностей
        except ValueError:
            # если вводимое название задачи "title" больше 100 символов, то возникает ошибка и мы ее обрабатываем
            return render(request, 'job/create_job_title.html', {'form': JobTitleForm(), 'error': 'Bad data passed in. Try again'})
            # переданы неверные данные. попробуйте еще раз

def currentjob(request):
    # пользователь видит все записи созданные всеми пользователями
    currentjobs = Job.objects.all().order_by('job_title')
    return render(request, 'job/current_job.html', {'currentjobs': currentjobs})

def viewjob(request, job_pk):
    # pk-первичный ключ (поиск объекта из базы по номеру ключа)
    job = get_object_or_404(Job, pk=job_pk)

    if request.method == 'GET':
        #для редактирования уже имеющийся заметки, записи
        form = JobTitleForm(instance=job)  # instance=1todo - уточняем, что изменяем уже существующий объект
        return render(request, 'job/view_job.html', {'job': job, 'form': form})
    else: # для сохранения отредактированой записи (заметки)
        try:
            form = JobTitleForm(request.POST, instance=job)
            # соединить внесенную информацию с нашей формой, instance=1todo - уточняем, что изменяем уже существующий объект
            form.save()
            return redirect('current_job')  # перенаправить пользователя на список записей
        except ValueError:
            return render(request, 'job/view_job.html', {'job': job, 'form': form, 'error': 'Bad info'})

def deletejob(request, job_pk):  # удалить задачу может только тот пользователь, к-ый создавал ее
    job = get_object_or_404(Job, pk=job_pk)
    if request.method == 'POST':
        job.delete()
        return redirect('current_job')  # перенаправить пользователя на список должностей

job/templates/job/base.html
{% load static %} <!-- загружаем папку статик -->
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'employees/custom.css' %}">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <link rel="icon" type="image/png" href="{% static 'employees/phone-book-contacts-svgrepo-com.svg' %}">
        <title>Справочник должностей</title>
    </head>

    <body>

        <nav class="navbar ml-auto bg-light">
            <div class="container justify-content-center">
                <div class="row col">
                    <div class="col">
                        <a href="{% url 'employees:create_employees' %}" class="btn btn-sm btn-outline-success"
                           type="button">Добавить сотрудника</a>
                        <a href="{% url 'employees:current_employees' %}" class="btn btn-sm btn-outline-secondary"
                           type="button">Список сотрудников</a>
                    </div>

                    <div id="start"></div>
                    <div class="col  text-center">
                        <a href="{% url 'home' %}">
                            <img src="{% static 'employees/home-svgrepo-com.svg' %}" width="30" height="30">
                        </a>
                    </div>

                    <div class="col">
                        <a href="{% url 'create_jobtitle' %}" class="btn btn-sm btn-outline-success"
                           type="button">Добавить должность</a>
                        <a href="{% url 'current_job' %}" class="btn btn-sm btn-outline-secondary"
                           type="button">Список должностей</a>
                    </div>
                </div>
            </div>
        </nav>


        <div class="container">
            {% block content %} {% endblock %}
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>

job/templates/job/create_job_title.html
{% extends 'job/base.html' %} <!-- привязка ранее созданного шаблона -->

{% block content %}

    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Новая должность</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="job_title">Должность</label>
                    <input type="text" name="job_title" class="form-control" id="job_title" required>
                </div>
                <div class="form-group">
                    <label for="job_category">Категория</label>
                    <input type="text" name="job_category" class="form-control" id="job_category" required>
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
        </div>
    </div>



{% endblock %}

job/templates/job/current_job.html
{% extends 'job/base.html' %} <!-- привязка ранее созданного шаблона -->
{% load static %} <!-- загружаем папку статик -->
{% block content %}



    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% if currentjobs %}
                <h1>Доступные должности</h1>
                всего({{ currentjobs.count }})
            {% else %}
                           <h1>Доступные должности</h1>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
        {% if currentjobs %}
            <div class="list-group">
                {% for currentjob in currentjobs %}
                    <a href="{% url 'viewjob' currentjob.id %}"
                       class="list-group-item list-group-item-action">
                        <b>{{ currentjob.job_title }}</b>
                        {{ currentjob.job_category }}
                    </a>
                {% endfor %} <!-- завершаем команду цикла -->
            </div>
        {% else %}
            <div class="text-center">
                <h2>Похоже, у Вас нет должностей!</h2>
            <br>
            <a role="button" class="btn btn-primary" href="{% url 'create_jobtitle' %}">Новая должность</a>
            </div>
        {% endif %}
        </div>
    </div>
    <br>
    <br>
<!-- стрелка для прокрутки страницы вверх -->
<div class = "fixed-bottom" style="margin-right: 16px; margin-bottom: 24px;">
    <div class= "d-flex justify-content-end">
        <a href = "#start"> <img src = "{% static 'employees/up-arrow-svgrepo-com.svg' %}" title="вверх" width="50" height="50"> </a>
    </div>
</div>

{% endblock %}

job/templates/job/home.html
{% extends 'job/base.html' %} <!-- привязка ранее созданного шаблона -->

{% block content %}


    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<div class="row justify-content-center mt-5">
    <div class="col-md-7 text-center">
        <h1>Cправочник должностей — тестовое задание на вакансию «инженер-программист»</h1>
        <br>
        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample3" role="button"
           aria-expanded="false" aria-controls="collapseExample">о проекте</a>
        <br>
        <div class="collapse" id="collapseExample3">
            <div class="container">
            <br>
                <li>Python 3.10</li>
                <li>Django 4.0.5</li>
                <li>Bootstrap 5.2.0</li>
                <li>Изначально была создана по умолчанию в Django БД "db.sqlite3".
                    Затем выполнена миграция БД на движке "postgresql_psycopg2" на хостинг heroku.com</li>
                <li>добавлена автоматическая сортировка сотрудников и должностей по алфавиту</li>
                <li>введено ограничение на ввод не буквенных символов в полях имя, фамилия, отчество</li>
                <li>введено ограничение на ввод возраста от 14 до 99</li>
            <br>
            </div>
        </div>
        <br>
        <hr>
    </div>
</div>


{% endblock %}

job/templates/job/professions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

job/templates/job/view_job.html
{% extends 'job/base.html' %} <!-- привязка ранее созданного шаблона -->

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Редактировать должность</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="job_title">Должность</label>
                    <input type="text" name="job_title" class="form-control" id="job_title"
                           value="{{ job.job_title }}" required>
                </div>
                <div class="form-group">
                    <label for="job_category">Категория</label>
                    <input type="text" name="job_category" class="form-control" id="job_category"
                           value= "{{ job.job_category }}" required>
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Сохранить</button>
<!--                <a href="{% url 'deletejob' job.id %}">Удалить</a>-->
                <button type="button" class="btn btn-danger" onclick="$('#delete').click()">Удалить</button>
            </form>
        </div>
    </div>

    <form style='display: none;' method="POST" action="{% url 'deletejob' job.id %}">
        {% csrf_token %}
        <button id="delete" type="submit">Delete</button>
    </form>
{% endblock %}