employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('currentemployees/', views.currentemployees, name='current_employees'),  # отображение всех созданых сотрудников
    path('createemployees/', views.createemployees, name='create_employees'),  # добавить сотрудника
    path('viewemployees/<int:employees_pk>', views.viewemployees, name='view_employees'),  # <int:employees_pk>/ - в адрес автомат-ки подставляет значение
    path('deleteemployee/<int:employee_pk>', views.deleteemployee, name='delete_employee'),
]

job_directory_project/urls.py
from django.contrib import admin
from django.urls import path, include
from job import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('currentjob/', views.currentjob, name='current_job'),  # отображение всех созданых должностей
    path('createjobtitle/', views.createjobtitle, name='create_jobtitle'),  # добавить должность
    path('viewjob/<int:job_pk>', views.viewjob, name='viewjob'),  # <int:job_pk>/ - в адрес автомат-ки подставляет значение
    path('deletejob/<int:job_pk>', views.deletejob, name='deletejob'),
    path('employees/', include('employees.urls'), name="employees_click")

]

employees/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator

class employees_Models(models.Model):
    # RegexValidator - регулярное выражение на проверку имени
    employees_Models_LastName = models.CharField(max_length=30, blank=True,
                                                 validators=[RegexValidator(r'^[a-zA-Zа-яА-Я]')])
    employees_Models_MidleName = models.CharField(max_length=30, blank=True,
                                                  validators=[RegexValidator(r'^[a-zA-Zа-яА-Я]')])
    employees_Models_FirstName = models.CharField(max_length=30, blank=True,
                                                  validators=[RegexValidator(r'^[a-zA-Zа-яА-Я]')])
    employees_Models_gender = models.CharField(max_length=10, blank=True)

    # проверка возраста от 14 до 99 лет
    employees_Models_age = models.IntegerField(blank=True, validators=[MinValueValidator(14), MaxValueValidator(99)])
    employees_Models_job = models.CharField(max_length=70, blank=True)

    def __str__(self):  # функция в отображении панели админа возращает не номера проектов, а заголовок проекта
        return self.employees_Models_FIO

employees/forms.py
from django.forms import ModelForm
from .models import employees_Models  # модель для объектов

class employeesForm(ModelForm):
    class Meta:
        model = employees_Models
        fields = ['employees_Models_LastName', 'employees_Models_MidleName',
                  'employees_Models_FirstName', 'employees_Models_gender',
                  'employees_Models_age', 'employees_Models_job']
        # что будем отображать - список

employees/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import employees_Models
from .forms import employeesForm
from job.models import Job

def createemployees(request):
    currentjobs = Job.objects.all()
    if request.method == 'GET':
        return render(request, 'employees/create_employees.html', {'form':employeesForm(), 'currentjobs':currentjobs})
    else:
        try:
            # выполняется если пользователь внес какую-то информацию в окно и нажал кнопку Create (Создать)
            form =employeesForm(request.POST)  # соединить внесенную информацию с нашей формой
            newemployees = form.save(commit=False)  # даная форму сохраняет информацию в базу данных
            # делаем привязку созданной записи к конкрутному пользователю
            newemployees.user = request.user
            newemployees.save()  # сохранит привязку в БД
            return redirect('employees:current_employees')  # перенаправить пользователя на список доступных сотрудников
        except ValueError:
            # если вводимое название задачи "title" больше 100 символов, то возникает ошибка и мы ее обрабатываем
            return render(request, 'employees/create_employees.html',
                          {'form': employeesForm(), 'currentjobs':currentjobs, 'error': 'Bad data passed in. Try again'})
            # переданы неверные данные. попробуйте еще раз


def currentemployees(request):
    # пользователь видит все записи созданные всеми пользователями
    currentemployees = employees_Models.objects.all().order_by('employees_Models_LastName')
    return render(request, 'employees/current_employees.html', {'currentemployees':currentemployees})

def viewemployees(request, employees_pk):
    # pk-первичный ключ (поиск объекта из базы по номеру ключа)
    employees = get_object_or_404(employees_Models, pk=employees_pk)
    currentjobs = Job.objects.all()
    if request.method == 'GET':
        #для редактирования уже имеющийся заметки, записи
        form = employeesForm(instance=employees)  # instance=1todo - уточняем, что изменяем уже существующий объект
        return render(request, 'employees/view_employees.html',
                      {'employees': employees, 'form': form, 'currentjobs':currentjobs})
    else: # для сохранения отредактированой записи (заметки)
        try:
            form = employeesForm(request.POST, instance=employees)
            # соединить внесенную информацию с нашей формой, instance=1todo - уточняем, что изменяем уже существующий объект
            form.save()
            return redirect('employees:current_employees')  # перенаправить пользователя на список сотрудников
        except ValueError:
            return render(request, 'employees/view_employees.html', {'employees': employees, 'form': form, 'error': 'Bad info'})


def deleteemployee(request, employee_pk):  # удалить задачу может только тот пользователь, к-ый создавал ее
    employees = get_object_or_404(employees_Models, pk=employee_pk)
    if request.method == 'POST':
        employees.delete()
        return redirect('employees:current_employees')  # перенаправить пользователя на список должностей

employees/templates/employees/create_employees.html
{% extends 'job/base.html' %} <!-- привязка ранее созданного шаблона -->

{% block content %}

    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h3>Новый сотрудник</h3>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="employees_Models_LastName">Фамилия</label>
                    <input type="text" name="employees_Models_LastName"
                           class="form-control" id="employees_Models_LastName" required>
                </div>
                <div class="form-group">
                    <label for="employees_Models_FirstName">Имя</label>
                    <input type="text" name="employees_Models_FirstName"
                           class="form-control" id="employees_Models_FirstName" required>
                </div>
                <div class="form-group">
                    <label for="employees_Models_MidleName">Отчество</label>
                    <input type="text" name="employees_Models_MidleName"
                           class="form-control" id="employees_Models_MidleName" required>
                </div>
                <label for="employees_Models_gender">Пол</label>
                <select class="form-control form-control-sm" name="employees_Models_gender" id="employees_Models_gender">
                    <option>муж.</option>
                    <option>жен.</option>
                </select>
                <div class="form-group">
                    <label for="employees_Models_age">Возраст</label>
                    <input type="text" name="employees_Models_age"
                           class="form-control" id="employees_Models_age" required>
                </div>

                {% if currentjobs %}
                    <label for="employees_Models_job">Должность</label>
                    <select class="form-control form-control-sm" name="employees_Models_job" id="employees_Models_job">
                        {% for currentjob in currentjobs %}
                            <option>{{ currentjob.job_title }} {{ currentjob.job_category }}</option>
                        {% endfor %}
                    </select>
                {% endif %}
                <br>
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
        </div>
    </div>



{% endblock %}

employees/templates/employees/current_employees.html
{% extends 'job/base.html' %} <!-- привязка ранее созданного шаблона -->
{% load static %} <!-- загружаем папку статик -->
{% block content %}

    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% if currentemployees %}
                <h1>Доступные сотрудники</h1>
                всего({{ currentemployees.count }})
            {% else %}
                <h1>Доступные сотрудники</h1>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
        {% if currentemployees %}
            <div class="list-group">
                {% for currentemployee in currentemployees %}
                    <a href="{% url 'employees:view_employees' currentemployee.id %}"
                       class="list-group-item list-group-item-action">
                        <b> {{ currentemployee.employees_Models_LastName }}
                            {{ currentemployee.employees_Models_FirstName }}
                            {{ currentemployee.employees_Models_MidleName }}
                        </b>
                            {% if currentemployee.employees_Models_gender == "муж." %}
                        <font color="blue">&#9794</font>
                            {% else %}
                        <font color="pink">&#9792;</font>

                            {% endif %}
                        <i>{{ currentemployee.employees_Models_age }} лет</i>
                        <u>{{ currentemployee.employees_Models_job }}</u>
                    </a>
                {% endfor %} <!-- завершаем команду цикла -->
            </div>
        {% else %}
            <div class="text-center">
                <h2>Похоже, у Вас нет сотрудников!</h2>
            <br>
            <a role="button" class="btn btn-primary" href="{% url 'employees:create_employees' %}">Новый сотрудник</a>
            </div>
        {% endif %}
        </div>

    </div>
    <br>
    <br>

<!-- стрелка для прокрутки страницы вверх -->
<div class = "fixed-bottom" style="margin-right: 16px; margin-bottom: 24px;">
    <div class= "d-flex justify-content-end">
        <a href = "#start"> <img src = "{% static 'employees/up-arrow-svgrepo-com.svg' %}" title="вверх" width="50" height="50"> </a>
    </div>
</div>

{% endblock %}

employees/templates/employees/view_employees.html
{% extends 'job/base.html' %} <!-- привязка ранее созданного шаблона -->

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Редактировать сотрудника</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="employees_Models_LastName">Фамилия</label>
                    <input type="text" name="employees_Models_LastName"
                           class="form-control" id="employees_Models_LastName"
                           value="{{ employees.employees_Models_LastName }}" required>
                </div>
                <div class="form-group">
                    <label for="employees_Models_FirstName">Имя</label>
                    <input type="text" name="employees_Models_FirstName"
                           class="form-control" id="employees_Models_FirstName"
                           value="{{ employees.employees_Models_FirstName }}" required>
                </div>
                <div class="form-group">
                    <label for="employees_Models_MidleName">Отчество</label>
                    <input type="text" name="employees_Models_MidleName"
                           class="form-control" id="employees_Models_MidleName"
                           value="{{ employees.employees_Models_MidleName }}" required>
                </div>
                <label for="employees_Models_gender">Пол</label>
                <select class="form-control form-control-sm" name="employees_Models_gender" id="employees_Models_gender">
                    <option>муж.</option>
                    <option>жен.</option>
                </select>
                <div class="form-group">
                    <label for="employees_Models_age">Возраст</label>
                    <input type="text" name="employees_Models_age"
                           class="form-control" id="employees_Models_age"
                           value="{{ employees.employees_Models_age }}" required>
                </div>

                {% if currentjobs %}
                    <label for="employees_Models_job">Должность</label>
                    <select class="form-control form-control-sm" name="employees_Models_job" id="employees_Models_job">
                        {% for currentjob in currentjobs %}
                            <option>{{ currentjob.job_title }} {{ currentjob.job_category }}</option>
                        {% endfor %}
                    </select>
                {% endif %}
                <br>

                <button type="submit" class="btn btn-primary">Сохранить</button>
                <button type="button" class="btn btn-danger" onclick="$('#delete').click()">Удалить</button>
            </form>
        </div>
    </div>

    <form style='display: none;' method="POST" action="{% url 'employees:delete_employee' employees.id %}">
        {% csrf_token %}
        <button id="delete" type="submit">Delete</button>
    </form>
{% endblock %}